services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: always
    hostname: "gitlab"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.matanweisz.xyz'
        registry_external_url 'https://registry.matanweisz.xyz'

        registry['enable'] = true
        registry['registry_http_addr'] = "0.0.0.0:5050"

        # ALB handles TLS termination
        nginx['listen_https'] = false
        nginx['listen_port'] = 80

        registry_nginx['enable'] = true
        registry_nginx['listen_https'] = false
        registry_nginx['listen_port'] = 5050

        nginx['real_ip_trusted_addresses'] = ['10.0.0.0/8', '172.16.0.0/12', '192.168.0.0/16']
        nginx['real_ip_header'] = 'X-Forwarded-For'
        nginx['real_ip_recursive'] = 'on'

        gitlab_rails['gitlab_shell_ssh_port'] = 2222
        gitlab_shell['ssh_port'] = 2222

        # Disable metrics
        prometheus_monitoring['enable'] = false
        alertmanager['enable'] = false
        node_exporter['enable'] = false
        redis_exporter['enable'] = false
        postgres_exporter['enable'] = false
        gitlab_exporter['enable'] = false

    ports:
      - "80:80"
      - "2222:22"
      - "5050:5050"
    volumes:
      - "gitlab_config:/etc/gitlab"
      - "gitlab_logs:/var/log/gitlab"
      - "gitlab_data:/var/opt/gitlab"
    shm_size: "256m"

volumes:
  gitlab_config:
  gitlab_logs:
  gitlab_data:
