# ArgoCD Application manifest
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp
  namespace: argocd
  labels:
    app: webapp

spec:
  project: default
  source:
    # Git repository containing your Helm chart
    repoURL: https://gitlab.matanweisz.xyz/matanweisz/helm-charts.git
    targetRevision: HEAD
    path: ./webapp
    
    # Helm configuration
    helm:
      valueFiles:
        - values.yaml

  # Destination configuration
  destination:
    server: https://kubernetes.default.svc
    namespace: webapp
  
  # Sync configuration
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    # Sync options
    syncOptions:
      - CreateNamespace=true    # Create namespace if it doesn't exist
      - Validate=true           # Validate manifests before applying

  # Revision history limit
  revisionHistoryLimit: 3  # Keep 3 previous revisions for rollback
